### PR TITLE
Added pcre

### PR DESCRIPTION
**Pull request by vadi2**
Addresses https://github.com/Mudlet/Mudlet/issues/872

Started on sound support as well, but commented out for now - to test one issue at a time.

Tagging @Mudlet/infrastructure for review

### CODE REVIEW

**Comment by vadi2** [comment]
Confirmed this fixes it for Fedora 25.

**Comment by vadi2** [comment]
Need to do the release and this is pretty non-controversial, so I'll merge it in for now. Let me know @keneanung if you'd like to revert.

**Comment by vadi2** [comment]
@SlySven mind blanket approving this?

**Comment by keneanung** [comment]
I'll have a look and approve in a few.

Vadim Peretokin <notifications@github.com> schrieb am Mi., 12. Apr. 2017,
19:31:

**Review by keneanung — APPROVED** [review]
Lools good to me

**Pull request merged**
