### PR TITLE
Sign inside the make-installer, only after we're done editing .app

### PR DESCRIPTION
**Pull request by vadi2**
We were signing the .app and then editing the contents of it - that's bad.

### CODE REVIEW

**Comment by keneanung** [comment]
Maybe we should use `security find-identity -s "$IDENTITY"` instead of checking for the `CERT_PW`. That way the script stays more general. Additionally, CERT_PW is not used, but IDENTITY is in the commands.

**Comment by keneanung** [comment]
See https://ss64.com/osx/security-find-id.html

**Comment by vadi2** [comment]
macos sierra running - oracle vm virtualbox_239

I'll stick with the current variant

**Comment by keneanung** [comment]
And how about `security find-identity | grep -q "$IDENTITY"` then check the exit status?

**Review by keneanung — APPROVED** [review]
Looks good

**Pull request merged**
