### PR TITLE
Add travis configuration and script to run shellcheck

### PR DESCRIPTION
**Pull request by keneanung**

### CODE REVIEW

**Comment by vadi2** [comment]
How did codacy get in here again?

**Review by vadi2 — APPROVED** [review]
Let's try testing it by breaking with a followup PR

**Comment by keneanung** [comment]
I broke it in https://travis-ci.org/keneanung/mudlet-installers/builds/221703883, but reset the commit

**Comment by keneanung** [comment]
About codacy.. I have no idea. I saw it as well and removed all the organisations/teams/projects I can reach from my account, hopefully that got rid of it...

**Comment by vadi2** [comment]
Aha nice.

**Pull request merged**
