### PR TITLE
Fix lua-zip to load

### PR DESCRIPTION
**Pull request by vadi2**
It required patching per https://github.com/probonopd/linuxdeployqt/issues/67

### CODE REVIEW

**Review by keneanung — CHANGES_REQUESTED** [review]
I do __not__ think we want to expand `$ORIGIN` at script runtime. Instead, we'd like it to be expanded at load time.

**Comment by vadi2** [comment]
It still seems to work and fixes the shellcheck error. What would you like it changed to?

**Comment by keneanung** [comment]
I suggest waiting until I can have a look at this, but I _believe_ we want to revert to 73335e9 and disable the shellcheck at those two lines instead.

**Comment by vadi2** [comment]
OK.

**Comment by keneanung** [comment]
So this is the output with `make-installer.sh` with your version:
```
22:17 $ ldd lib/zip.so 
	linux-vdso.so.1 =>  (0x00007fff49886000)
	libzzip-0.so.13 => /usr/lib/x86_64-linux-gnu/libzzip-0.so.13 (0x00007f800494b000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f8004584000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f8004368000)
	/lib64/ld-linux-x86-64.so.2 (0x000055e3dae52000)
```

And this is the output with the call as `patchelf --set-rpath '$ORIGIN' lib/zip.so`:
```
22:21 $ ldd lib/zip.so 
	linux-vdso.so.1 =>  (0x00007ffc97b98000)
	libzzip-0.so.13 => /home/keneanung/git/Mudlet-installers/generic-linux/build/lib/libzzip-0.so.13 (0x00007efc60655000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007efc6025d000)
	libz.so.1 => /home/keneanung/git/Mudlet-installers/generic-linux/build/lib/libz.so.1 (0x00007efc60041000)
	/lib64/ld-linux-x86-64.so.2 (0x00005603f91e9000)
```

As you can see, the first version is trying to load the `libz.so` from my system (which is wrong), while the second one loads it (more or less) relative to the `zip.so`. Turning off the shellsheck warning seems to be the way to go here.

**Comment by vadi2** [comment]
OK, fixed it up.

**Review by keneanung — APPROVED** [review]
Great!

**Pull request merged**
